### ISSUE TITLE
Error in script zabbix-whois-check.py

### ISSUE THREAD

**Issue by jchelp** [okand/zabbix-whois-expiry#3]
Good morning I'm deploying your script the discovery runs correctly, but checy returns this error
 File "./zabbix-whois-check.py", line 22
    if isinstance(w.expiration_date, list):
                                          ^
TabError: inconsistent use of tabs and spaces in indentation

I'm using ubuntu 18.4

**Comment by okand** [comment]
Hi.

Thanks for noticing and pointing this out. I haven't used this script in a long time myself but I downloaded a copy to check in an editor and there is indeed an inconsistent mix of tabs and spaces in that section (dots and then suddenly an arrow when showing whitespace characters).
![](https://i.imgur.com/jnOwUuw.png)

Python uses these characters to identify which pieces of code should follow or be skipped. I've committed an update that makes this consistent now.
